name: Deploy to Heroku

on:
    push:
        tags: [v*.*.*]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Login to Heroku Registry
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
              run: |
                  heroku container:login

            - name: Build and push
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
                  HEROKU_APP_NAME: silver-happiness
                  HD_NODE_ENV: production
                  HD_PORT: 8080
                  HD_MONGO_HOST: ${{secrets.MONGO_HOST}}
                  HD_MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
              run: heroku container:push web --app $HEROKU_APP_NAME

            - name: Release
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
                  HEROKU_APP_NAME: silver-happiness
                  HD_NODE_ENV: production
                  HD_PORT: 8080
                  HD_MONGO_HOST: ${{secrets.MONGO_HOST}}
                  HD_MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
              run: heroku container:release web --app $HEROKU_APP_NAME
