name: Deploy to Heroku

on:
    push:
        tags: [v*.*.*]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Login to Heroku Registry
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
              run: |
                  heroku login --api-key $HEROKU_API_KEY

            - name: Build and push
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
                  HEROKU_APP_NAME: silver-happiness
              run: heroku container:push web --app $HEROKU_APP_NAME

            - name: Release
              env:
                  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
                  HEROKU_APP_NAME: silver-happiness
              run: heroku container:release web --app $HEROKU_APP_NAME
